### ISSUE TITLE
Jamie's Thanksgiving Checklist

### ISSUE THREAD

**Issue by JamieCrisman** [UTD-CRSS/app.exploreapollo.org#26]
- [x] Homepage (mission selection?) (maybe a coming soon for the other missions)
- [x] Click on transcript line to jump to that time
- [x] Moments connected to dummy data
- [x] Connect API to front-end: moments (Austin?)
- [x] Connect API to front-end: stories (Austin?)

**Comment by JamieCrisman** [comment]
https://github.com/UTD-CRSS/app.exploreapollo.org/pull/27 finishes up connecting stuff to dummy data

**Comment by JamieCrisman** [comment]
https://github.com/UTD-CRSS/app.exploreapollo.org/pull/28 better placeholder landing page (heh landing page)

**Comment by JamieCrisman** [comment]
https://github.com/UTD-CRSS/app.exploreapollo.org/pull/29 transcript messages are clickable. will set the audio time to the start time of the transcript

**Comment by austinpray** [comment]
This looks good, let me handle the API stuff
